# Generated by Django 3.2 on 2022-03-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='buyer',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
