# Generated by Django 3.2 on 2022-03-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_alter_product_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
