# Generated by Django 3.2 on 2022-03-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_auto_20220317_2056'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='mall_user',
        ),
    ]
