# Generated by Django 3.2 on 2022-03-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0006_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
